apiVersion: hmc.mirantis.com/v1alpha1
kind: ServiceTemplate
metadata:
  name: external-secrets-0-11-0
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartName: external-secrets
    chartVersion: 0.11.0
